### ISSUE TITLE
ASTRA CPU reconstruction returning zero array

### ISSUE THREAD

**Issue by dmpelt** [tomopy/tomopy#195]
Created a new issue for the discussion at #191, which became a bit off-topic.

To summarize: ASTRA CPU reconstructions are returning a zero array on @AoxiangGeng's machine. I think the `multiprocessing` module is suppressing any error message that is thrown.

@AoxiangGeng: ASTRA seems to be installed correctly on your machine. What version of TomoPy are you running and how did you install it? There was a recent update to TomoPy that broke ASTRA integration for a few days, so maybe you are using this version. Just to find out a bit more what is going on, could you try the following reconstruction using CUDA? I know it won't work since you don't have a GPU installed, but it will be useful to see whether it gives an error / will crash / will return a zero array.

```python
rec = tomopy.recon(data, angles, 
    algorithm=tomopy.astra, options={'method':'FBP_CUDA', 'proj_type':'cuda'})
```

**Comment by SebastianArmin** [comment]
Hi Dmpelt,

I ran the code and there is an ImportError , shows that:
File

'../anaconda2/lib/python2.7/site-packages/astra/matlab.py" line 38 in
<module>
    from . import astra.c
ImportError:/lib64/libc.so.6:version 'GLIBC_2.14' not found.

What should I try now?

**Comment by AoxiangGeng** [comment]
Hi Dmpelt,

I ran the code and there is an ImportError , shows that:
File

'../anaconda2/lib/python2.7/site-packages/astra/matlab.py" line 38 in

from . import astra.c
ImportError:/lib64/libc.so.6:version 'GLIBC_2.14' not found.

What should I try now?

**Comment by dmpelt** [comment]
Ah, that is very useful information. This means that the libc version of your machine is significantly older than the libc version that astra was build with (see [here](http://superuser.com/questions/537683/how-to-fix-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-14-not-found/)). I think the oldest version of glibc that is supported is 2.14, which was released in 2011.

One solution is to update libc on the machine, but if that is not possible a different solution is to compile ASTRA on the machine itself. I remember that a different machine was having this problem as well, and compiling ASTRA was the easiest solution there.

Compiling ASTRA (either using conda or not) should be quite easy (see [here](http://www.astra-toolbox.com/en/latest/docs/install.html)). The following is a simple example:
```bash
git clone --depth 1 https://github.com/astra-toolbox/astra-toolbox.git
cd astra-toolbox/build/linux
./autogen.sh
./configure --with-python --prefix=$HOME/astrapref/
make -j 8 install
export PYTHONPATH=$HOME/astrapref/python/:$PYTHONPATH
export LD_LIBRARY_PATH=$HOME/astrapref/lib/:$LD_LIBRARY_PATH
```

**Comment by AoxiangGeng** [comment]
OK， now I have compiled ASTRA using this example. But when I go back to run the previous code with CUDA, the program seems won't stop. And if I force it to stop and run the astra method 'FBP' with proj_type'line', still return an empty result.

**Comment by dmpelt** [comment]
Can you try to run the code example in `samples/python/s004_cpu_reconstruction.py` of the astra toolbox source repository? This will show whether astra is working correctly.

**Comment by AoxiangGeng** [comment]
Ok, seems that it is still the libc problem... I will try to update it on
the server and come back to you then. Thanks a lot!!

2016-04-22 16:33 GMT+02:00 Daniel M. Pelt <notifications@github.com>:

**Comment by AoxiangGeng** [comment]
Hi Dmpelt,

We fixed the last problem finally... But when we run the text function ,there is a new error:
ImportError: no module named astra.

Do you have an idea of how to fix that? Because when we run the installation there is no error.

**Comment by dmpelt** [comment]
The error indicates that astra is not installed in the python environment that you are running. 

Can you give some more details on how you did the astra installation? If you compiled astra, the folder that you installed astra in (the `prefix` option of `configure`) should be added to the `PYTHONPATH` environment variable, like:
```bash
export PYTHONPATH=[/path/to/astra/prefix]/python:$PYTHONPATH
```

**Comment by AoxiangGeng** [comment]
THis is how we install astra:

git clone https://github.com/decarlof/astra-toolbox astra

cd astra/

git branch -a

git checkout -b 1.6.1b origin/1.6.1b

export CUDA_ROOT='/usr/local/cuda/'

echo $CUDA_ROOT

conda build ./

conda install --use-local astra-toolbox

In this one , we didn't compile astra. Instead we updated glibc. And the astra is downloaded into the root folder not in the python's folder. Does that matter?

**Comment by dmpelt** [comment]
Is there a reason why you are using the decarlof astra repository? The official one is `https://github.com/astra-toolbox/astra-toolbox`, and decarlof's repository is a (very) old version, which does not support building with conda. Also, the conda build files are in the `python/conda` folder, so I think the above commands actually do not install anything, which explains why astra was not installed. 

To use the latest version and the correct conda folder with the same approach as above, try:

```bash
git clone https://github.com/astra-toolbox/astra-toolbox astra
cd astra/
git branch -a
git checkout tags/v1.7.1
export CUDA_ROOT='/usr/local/cuda/'
echo $CUDA_ROOT
cd python/conda/
MAKEOPTS="-j 8" conda build ./
conda install --use-local astra-toolbox
```

**Comment by AoxiangGeng** [comment]
Wow, thanks for the recommendation.  Someone send me that code for installation and I simply tried it 

But here, when I ran "MAKEOPTS="-j 8" conda build ./", it shows that "./autogen.sh command not found." However, when I checked the document of astra. There is a file called autogen.sh

Sorry for bothering all the time on this issue...

**Comment by dmpelt** [comment]
Can you post the complete output of all commands? The only thing I can think of at the moment is that compiling astra requires that `automake`, `autoconf`, and `libtool` are installed on the machine. I just tried the commands I posted on a clean conda environment on my machine, and it worked without problems.

Also, if you have updated glibc on the machine, installing an official astra conda build (without compiling it) should work now:
```bash
conda install -c astra-toolbox astra-toolbox
```
Can you try that as well?

**Comment by AoxiangGeng** [comment]
I tried this one before I use that old version, and it returns: Package missing in current linux-32 channels. Then I tried it on a Mac and still shows that Package missing in current channels.

For the complete output. There is just one error shows "./autogen.sh command not found" when I do " MAKEOPTS="-j 8" conda build ./" . The other commands ran perfectly. And there is even no problem when I ignore this error and ran "conda install --use-local astra-toolbox". But when I tried the test function it tells me no module named astra. 

I remember when I tried another way to install astra it had the same error:
cd build/linux
./autogen.sh   # Here the error happened
./configure --with-cuda=/usr/local/cuda \
            --with-matlab=/usr/local/MATLAB/R2012a \
            --with-python
            --prefix=/usr/local/astra
make
make install

**Comment by dmpelt** [comment]
Very strange! I am sure we can get to the bottom of this. The fact that the conda install call does not work is because your machine is running a 32-bit linux OS (I haven't seen one of those in years!) and we only have 64-bit binaries available. In this case the best solution is indeed to manually compile the toolbox with the commands I posted above.

To check whether the required programs are installed, can you try to run the following on the machine:
```bash
which aclocal
which autoconf
which libtoolize
```

PS. I have to leave soon so it may take me a while to reply.

**Comment by AoxiangGeng** [comment]
Aha, aclocal is not installed! So that is the trouble maker. Well now I am trying on a 64-bit Mac computer. Ok, I also have to go, but maybe I should figure out how to fix aclocal before Monday.

Thanks a lot . Have a good weekends!

**Comment by fpanerai** [comment]
Hi guys, 

I'm joining the conversation as I'm running into the same issue. My situation is a bit further complicated by the fact that I don't have root privileges and I'm trying to get this running in my home directory. 

I can import tomopy in python3 installed with conda. This works fine.

I have installed astra with: 
`git clone --depth 1 https://github.com/astra-toolbox/astra-toolbox.git`
`cd /u/wk/fpanerai/tools/astra-toolbox/build/linux/`
`./autogen.sh`
`./configure --with-python --prefix=u/wk/fpanerai/tools/astra-toolbox/astra-install/`
`make -j 8 install`
All worked fine.

I then added this to my .cshrc:
`setenv PYTHONPATH /u/wk/fpanerai/tools/astra-toolbox/astra-install/python`
`setenv LD_LIBRARY_PATH /u/wk/fpanerai/tools/astra-toolbox/astra-install/lib`
If I `echo $PYTHONPATH` I get  `/u/wk/fpanerai/tools/astra-toolbox/astra-install/python`
and if I `echo LD_LIBRARY_PATH` I get `/u/wk/fpanerai/tools/astra-toolbox/astra-install/python`
So everything seems fine here as well.

Now if I run `python3` and then `import astra`, I get the same issue:
`  File "<stdin>", line 1, in <module>`
`  File "/u/wk/fpanerai/tools/astra-toolbox/astra-install/python/astra/__init__.py", line 26, in <module>`
`    from . import matlab as m`
`  File "/u/wk/fpanerai/tools/astra-toolbox/astra-install/python/astra/matlab.py", line 38, in <module>`
`    from . import astra_c`
`ImportError: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /u/wk/fpanerai/anaconda3/lib/libastra.so.0)`

Looks like it is trying to still look for glibc. Any idea? Sorry if this looks really dumb but I'm really unable to fix it.

Thanks! 
Francesco

**Comment by fpanerai** [comment]
I also installed a recent glibc release in my local home, but when I try to set my env path in the cshrc I get a segmentation fault error and cannot used the terminal anymore.

**Comment by decarlof** [comment]
@fpanerai Hi Francesco, 
I was getting the very same error after conda install astra on RedHat. Tried also the upgrade of glibc and failed. I solved it by building conda on my red hat machine from source.
Are you on RedHat too?

ciao
f

**Comment by fpanerai** [comment]
@decarlof Hi Francesco, 
Yes, I'm on RedHat as well. I believe I built conda from source, but this was some time ago and I may have not done it properly. I will re-install it and see if it helps. Did you install astra from conda, after building conda? I've also asked support to NAS HECC (where the workstation belongs) to upgrade glibc and gcc, as I had convinced myself this might be useful, but I'm actually not sure anymore.
Thanks for your help, 
Francesco

**Comment by tacaswell** [comment]
LCLS also uses RHEL and have been working an getting coda to work correctly for them.  @chrisvam can probably point you to the right people there to talk to.

**Comment by chrisvam** [comment]
I don't know if it helps, but we're using conda with python 2.7 on RHEL7.  I was able to successfully do
`conda install -c astra-toolbox astra-toolbox` and then "import astra" seemed to work inside python.  But it looks like our RHEL7 has libc 2.17, so perhaps that's recent enough.  Our RHEL6 looks like it has libc 2.12 and our RHEL5 looks like it has libc 2.5.

As an aside, we're still learning, but this is one of the things that scares me about conda:  distributing one set of binaries that work on all "linux" platforms seems challenging.

**Comment by lylofu** [comment]
Hi dmpelt,

We got some problem installing ASTRA. We followed the way that you suggested:
git clone https://github.com/astra-toolbox/astra-toolbox astra
cd astra/
git branch -a
git checkout tags/v1.7.1
export CUDA_ROOT='/usr/local/cuda/'
echo $CUDA_ROOT
cd python/conda/
MAKEOPTS="-j 8" conda build ./
conda install --use-local astra-toolbox

But when we run MAKEOPTS="-j 8" conda build ./, there is an error says:
Package: astra-toolbox-1.7.1-py27_0
source tree in: /Users/ademortiere/anaconda/conda-bld/work
+ cd build/linux
+ ./autogen.sh
./autogen.sh: line 20: glibtoolize: command not found
Error running libtoolize
Command failed: /bin/bash -x -e /Users/ademortiere/anaconda/astra/python/conda/build.sh

So we tried to install libtool with 'brew install libtool'; it returned : libtoolinstalled, it is just not linked.
But when we do 'brew link libtool, it returned:Error: Could not symlink include/libltdl/lt_dlloader.h
/usr/local/include/libltdl is not writable.
Even if we tried 'sudo brew link libtool' it still didn't work.

So we guess there might be another option and we tried to rewrite the autogen.sh file in astra/build/linux, we changed all the glibtoolize to libtoolize, still didn't work.

Can you help us?

**Comment by lylofu** [comment]
Also , we tried to install astra with:
conda install -c astra-toolbox astra-toolbox

and then do : 
export PYTHONPATH=[/Users/ademortiere/anaconda/astra]/python:$PYTHONPATH

But when we run the test function it returned: ImportError, No module named astra.

**Comment by fpanerai** [comment]
Hi all,

Here is a quick update. Thanks @chrisvam, I managed to solve the issue with your hint!

I'm running on RHEL6 and the problem is indeed the libc system version (2.12), versus the one required (2.14) by astra. I locally installed the latest glibc release and tried to set LD_LIBRARY_PATH into .cshrc. This would give me a segmentation fault error, as the local libc conflicted with the system one. To circumvent this, I built astra from sources, by changing the directories to the system library path in the configure script. 

After installing your local version (>=2.14) of libc, edit `your-astra-path/astra-toolbox/build/linux/configure` and replace  `sys_lib_dlsearch_path_spec="/lib64 /usr/lib64 /lib /usr/lib"` with `sys_lib_dlsearch_path_spec="your-local-glibc-install-path/lib /usr/lib64 /lib /usr/lib"`.

Then build astra with:
`./configure --with-python=python3 --prefix=your-astra-install-path/`
`make`
`make install`
(or simply `--with-python` if you run v2)

Then add:
`setenv PYTHONPATH your-astra-install-path/python`
`setenv LD_LIBRARY_PATH your-astra-install-path/lib:$LD_LIBRARY_PATH`
to your .cshrc and source it. Similar if you use bash instead of csh.

Make sure you remove your conda astra package if you have previously installed any. In my case it actually worked only when I unistalled the whole conda distribution and re-installed it.

Hope this helps, 
Francesco

**Comment by dmpelt** [comment]
Hi all,

Sorry for not replying for a while, I had my PhD defense last week so was quite busy with that.

I think there are a two separate issues discussed here:

1. Installing ASTRA using conda on a machine with an old libc version (RHEL <=6).
2. Compiling/installing ASTRA on Mac OSX.

Regarding 1), I think this is not trivial to fix in a nice way. Installing a more recent libc version using conda will probably result in breaking system packages, so I would not suggest that. The easiest solution is to compile ASTRA using the old system libc version. In this case, please make sure to uninstall the (not-working) package installed with conda first (`conda uninstall astra-toolbox`), as it will be prioritized over the self-compiled version. If there are still problems, it is probably best to try recompiling in a new clean conda environment, and with a clean astra download. I think the easiest way to compile ASTRA is to use the 'Linux, from source' from [here](http://www.astra-toolbox.com/docs/install.html). As a more general solution, I could try to create a separate conda build using an old libc version, and upload it to conda under a different name.

Regarding 2), we do not officially support Mac OSX yet, although I've heard reports that it is possible to compile and install it with a bit of work, and we do have a bit of code included that would help. However, I don't know whether compiling with CUDA works at the moment, and I don't have a Mac machine to test things on, so unfortunately I can't help much with any osx-specific problems.

**Comment by dmpelt** [comment]
@lylofu @AoxiangGeng  I will try to find an OSX machine to test on, and will try to create a conda package for OSX. I don't think installing ASTRA will work at the moment on OSX unfortunately, only Linux and Windows are supported right now. I will let you know once I get it working.

@chrisvam @fpanerai I recently created a PyPI package for ASTRA that will do all the compiling for you, with the system libc version. In a completely clean `pip` environment, and with all previous ASTRA installations removed (for example those in `/usr/local/astra`), a `pip install astra-toolbox` call should correctly compile and install ASTRA in the correct location. If you want to use CUDA, please do the following:

```bash
CUDA_ROOT=/path/to/cuda pip install astra-toolbox
```

Compilation will take a long time, but you can also add `MAKEOPTS="-j 16"` at the start of the line to compile with 16 parallel jobs. Again, compiling and installing with `pip` will only work on Linux, not on OSX.

Please let me know if you run into any problems.
